version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000" # Замените порт, если требуется
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: linkedin